### ISSUE TITLE
branch master is not compiling with jdk7 or jdk8

### ISSUE THREAD

**Issue by spyhunter99** [openwide-java/owsi-core-parent#64]
on windows, getting test failures

````
[INFO] ------------------------------------------------------------------------
[INFO] Building OWSI Core - Component - Commons 0.12-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce) @ owsi-core-component-commons ---
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (clean-generated-sources) @ owsi-core-component-commons ---
[INFO] Deleting C:\projects\owsi-core-parent\owsi-core\owsi-core-components\owsi-core-component-commons\target\generated-sources\apt (includes = [], excludes = [])
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (clean-generated-test-sources) @ owsi-core-component-commons ---
[INFO]
[INFO] --- maven-processor-plugin:3.1.0:process (maven-processor-plugin-default) @ owsi-core-component-commons ---
[WARNING] diagnostic: warning: Supported source version 'RELEASE_6' from annotation processor 'org.bindgen.processor.Processor' less than -source '1.7'
[WARNING] diagnostic: warning: The following options were not recognized by any processor: '[fullyAnnotationConfigured, addSuppressWarningsAnnotation]'
[INFO]
[INFO] --- maven-resources-plugin:3.0.0:resources (default-resources) @ owsi-core-component-commons ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\projects\owsi-core-parent\owsi-core\owsi-core-components\owsi-core-component-commons\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ owsi-core-component-commons ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 126 source files to C:\projects\owsi-core-parent\owsi-core\owsi-core-components\owsi-core-component-commons\target\classes
[INFO] /C:/projects/owsi-core-parent/owsi-core/owsi-core-components/owsi-core-component-commons/target/generated-sources/apt/org/bindgen/java/util/DateBindingPath.java: C:\projects\owsi-core-parent\owsi-core\owsi-core-components\owsi-core-component-commons\target\generated-sources\apt\org\bindgen\java\util\DateBindingPath.java uses or overrides a deprecated API.
[INFO] /C:/projects/owsi-core-parent/owsi-core/owsi-core-components/owsi-core-component-commons/target/generated-sources/apt/org/bindgen/java/util/DateBindingPath.java: Recompile with -Xlint:deprecation for details.
[INFO]
[INFO] --- animal-sniffer-maven-plugin:1.15:check (check-java-version) @ owsi-core-component-commons ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java17:1.0
[INFO]
[INFO] --- maven-processor-plugin:3.1.0:process-test (maven-processor-plugin-default-test) @ owsi-core-component-commons ---
[WARNING] diagnostic: warning: Supported source version 'RELEASE_6' from annotation processor 'org.bindgen.processor.Processor' less than -source '1.7'
[WARNING] diagnostic: warning: The following options were not recognized by any processor: '[fullyAnnotationConfigured, addSuppressWarningsAnnotation]'
[INFO]
[INFO] --- maven-resources-plugin:3.0.0:testResources (default-testResources) @ owsi-core-component-commons ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] ignoreDelta true
[INFO] Copying 3 resources
[INFO] Copying file FileUtils\test.zip
[INFO] Copying file FileUtils\test1.txt
[INFO] Copying file FileUtils\test2
[INFO]
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ owsi-core-component-commons ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 8 source files to C:\projects\owsi-core-parent\owsi-core\owsi-core-components\owsi-core-component-commons\target\test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ owsi-core-component-commons ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running fr.openwide.core.test.commons.util.functional.converter.ConvertersTest
Tests run: 36, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.207 sec - in fr.openwide.core.test.commons.util.functional.converter.ConvertersTest
Running fr.openwide.core.test.commons.util.mime.TestMediaType
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in fr.openwide.core.test.commons.util.mime.TestMediaType
Running fr.openwide.core.test.commons.util.TestCloneUtils
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in fr.openwide.core.test.commons.util.TestCloneUtils
Running fr.openwide.core.test.commons.util.TestFileUtils
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec <<< FAILURE! - in fr.openwide.core.test.commons.util.TestFileUtils
testList(fr.openwide.core.test.commons.util.TestFileUtils)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError
        at fr.openwide.core.test.commons.util.TestFileUtils.testList(TestFileUtils.java:73)

testGetFile(fr.openwide.core.test.commons.util.TestFileUtils)  Time elapsed: 0 sec  <<< FAILURE!
java.lang.AssertionError
        at fr.openwide.core.test.commons.util.TestFileUtils.testGetFile(TestFileUtils.java:30)

Running fr.openwide.core.test.commons.util.TestSerializableCollator
Tests run: 120, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.287 sec - in fr.openwide.core.test.commons.util.TestSerializableCollator
Running fr.openwide.core.test.commons.util.validator.TestAnyTldDomainValidator
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec - in fr.openwide.core.test.commons.util.validator.TestAnyTldDomainValidator
Running fr.openwide.core.test.commons.util.validator.TestAnyTldUrlValidator
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 sec - in fr.openwide.core.test.commons.util.validator.TestAnyTldUrlValidator
Running fr.openwide.core.test.commons.util.validator.TestPermissivePhoneNumberValidator
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in fr.openwide.core.test.commons.util.validator.TestPermissivePhoneNumberValidator

Results :

Failed tests:
  TestFileUtils.testGetFile:30
  TestFileUtils.testList:73

Tests run: 193, Failures: 2, Errors: 0, Skipped: 0
````

**Comment by lalmeras** [comment]
Hi,

I just push b9d3d63f282e979b407fb91ad0e890b0eb821c1e which should fix these failures. I delete useless tests that rely on unspecified jvm behavior (File#length() on http://docs.oracle.com/javase/6/docs/api/java/io/File.html#length%28%29) and that never fail on our Linux environments.

Can you confirm it fixes your issue ?

About jdk7 and 8, currently we only distribute jdk7 artifacts (built with jdk7 but runnable with jdk8), so derived projects are also constrained to jdk7 _building_ (because one component, bindgen - a code generator -, generates different output for jdk7 and jdk8).
However, full jdk8 building should be possible, and I'm willing to work on it.
